export const MARKETS = [
    { id: 'US', name: 'US Market', currency: 'USD', flag: '🇺🇸' },
    { id: 'IN', name: 'Indian Market', currency: 'INR', flag: '🇮🇳' },
    { id: 'CN', name: 'Chinese Market', currency: 'CNY', flag: '🇨🇳' },
    { id: 'EU', name: 'European Market', currency: 'EUR', flag: '🇪🇺' },
    { id: 'JP', name: 'Japanese Market', currency: 'JPY', flag: '🇯🇵' },
    { id: 'SG', name: 'Singapore Market', currency: 'SGD', flag: '🇸🇬' },
    { id: 'KR', name: 'South Korean Market', currency: 'KRW', flag: '🇰🇷' },
    { id: 'CRYPTO', name: 'Crypto Market', currency: 'USD', flag: '₿' },
    { id: 'FOREX', name: 'Forex Market', currency: 'USD', flag: '💱' },
    { id: 'COMMODITIES', name: 'Commodities Market', currency: 'USD', flag: '🛢️' },
];

export const STOCK_NAMES = {
    '7267.T': 'Honda Motor Co., Ltd.',
    'AAPL': 'Apple Inc.',
    'GOOGL': 'Alphabet Inc.',
    'MSFT': 'Microsoft Corporation',
    'AMZN': 'Amazon.com Inc.',
    'TSLA': 'Tesla, Inc.',
    'RELIANCE.NS': 'Reliance Industries',
    'TCS.NS': 'Tata Consultancy Services',
    'INFY.NS': 'Infosys Limited',
    'HDFCBANK.NS': 'HDFC Bank',
    'BTC-USD': 'Bitcoin',
    'ETH-USD': 'Ethereum',
    'EUR/USD': 'Euro / US Dollar',
    'GBP/USD': 'British Pound / US Dollar',
    'JPY/USD': 'Japanese Yen / US Dollar',
    '005930.KS': 'Samsung Electronics',
    '600519.SS': 'Kweichow Moutai',
    '9988.HK': 'Alibaba Group',
    '7203.T': 'Toyota Motor Corp',
    '6758.T': 'Sony Group Corp',
    'DBS': 'DBS Group Holdings',
};
